# Introduction

`r actionLink(ns("intro1"), "✅ Social isolation in humans leads to decreased well-being, depression, increased mortality, and, especially in the elderly, cardiovascular disease, cerebrovascular disease, and cognitive decline [1–5].", class = "highlight_green")` In addition, changes in eating habits, decreased activity, and reduced walking speed and ADLs (Activities of Daily Living) may be associated with physical frailty [6–9].
<br></br>
Social isolation is also considered to be a factor in `r actionLink(ns("intro_vocab1"), "✏️ social frailty", class = "highlight_purple")`, and the presence of social frailty has been reported to affect diet quality, food intake, and nutritional status, especially in elderly men, suggesting that it may contribute to the risk of low nutrition [10]. Recently, some studies have found that increased physical frailty is due to changes in eating habits and decreased physical activity levels, which were caused by increased social isolation during the coronavirus disease 2019 pandemic; therefore, support is needed to prevent undernutrition, including the elimination of social isolation [11, 12]. As people age, death and disability increase among their social circles, and the size of their social networks shrinks. For this reason, social isolation is often unavoidable [13, 14]. Therefore, methods that reduce the effects of social isolation on those living in isolated environments are needed.
<br></br>
In several studies, the effects of social isolation were found to be intricately related to a variety of confounding factors; including living environment; geographic factors related to where the person resides; social resource factors, such as relatives and friends; and economic factors [14]. Because social isolation is complicated by confounding factors, clinical research with human participants is limited. `r actionLink(ns("intro2"), "✅ On the other hand, animal experiments can reproduce the isolated state model without considering multiple confounding factors. Previous animal studies have demonstrated that chronic psychological stress in isolation affects body weight, food intake, and physical activity. Depending on age and sex, varying effects have been observed, which have been suggested to be due to peripheral and central ghrelin and adaptive capacity [15, 16].Previous studies have not sufficiently examined the effects of social isolation on the body and the effectiveness of environmental changes for rats of any age.", class = "highlight_green")`  `r actionLink(ns("intro3"), "❓ Studies with older rats are needed; however, as in similar studies [17, 18], we chose to study young rats first as a preliminary study.", class = "highlight_pink")`
<br></br>
`r actionLink(ns("intro4"), "✅ The purpose of this study was to clarify the unexplored effects of social isolation and to determine whether environmental changes as an intervention against social isolation can reduce the stress-inducing effects of social isolation on physiological factors.", class = "highlight_orange")`