# Effect of Caffeine on Heart Rate and Blood Pressure

Abstract- Caffeine increases systolic blood pressure to extent of 17% and mean arterial blood pressure by about 11%. Heart rate was also increased. The increase in systolic blood pressure was attributed more to the increased stiffness of the aorta and larger blood vessels rather than increased stroke volume. The increase of aortic stiffness is attributed to the increased production of angiotensin II and catecholamines potentially nor adrenaline. These changes are attributable to the inhibition of adenosine A2a receptors activity in the smooth muscles of blood vessels. The concomitant increase in the release of rennin from the kidneys because of the direct stimulation by caffeine and similar activity on sympathetic ganglions releasing noradrenaline contributes to the increased activity of vascular smooth muscles. In the present study, attempt has been made to know the changes occurring in heart rate and blood pressure after the intake of caffeine.
