# Cardiac fibrosis induced by high-fat diet in ApoE-deficient male mice is exacerbated by genetic deletion of PACAP–PAC1 signaling

Fibrosis is a hallmark of cardiac remodeling and is present in a wide variety of cardiac diseases [1]. Reparative fibrosis occurs, for example, after myocardial infarction to preserve the structural integrity of the heart and thus prevent fatal cardiac rupture. In addition, there is cardiac fibrosis that primarily affects the interstitium [2]. This type of cardiac fibrosis develops insidiously without loss of cardiomyocytes and is characterized by interstitial and perivascular deposition of extracellular matrix (ECM) proteins [3]. As a result, myocardial stiffness increases and ventricular compliance decreases, leading to diastolic dysfunction. Interstitial fibrosis is a pivotal factor contributing to heart failure, for example, in the syndrome of heart failure with preserved ejection fraction (HFpEF) [4]. Current evidence suggests that comorbidities, predominantly from the metabolic spectrum, such as obesity, diabetes mellitus and arterial hypertension, are potent drivers of chronic systemic low-grade inflammation and constitute a cardinal pro-fibrotic stimulus in many cardiac diseases including HFpEF [5, 6]. `r actionLink(ns("practice_intro3_mystery1"), "Whereas several prognosis-improving pharmacological therapies are available for heart failure in which reparative fibrosis (e.g., after myocardial ischemia) plays a central role, the therapeutic options for non-reparative/interstitial fibrosis (e.g., associated with the metabolic syndrome) are very limited and new options are urgently needed, given the high prevalence of related morbidities [7]. ", class = "invisible_yellow")`

A growing body of evidence for cardioprotective effects of the neuropeptide pituitary adenylate cyclase-activating peptide (PACAP) renders it a promising candidate for further research in this area. PACAP belongs to the vasoactive intestinal polypeptide (VIP)/secretin/somatoliberin/glucagon superfamily and exhibits evolutionary conservation with complete homology among mammalian species [8]. The peptide is present in two isoforms: PACAP-27 and PACAP-38, which are 27 or 38 amino acid residues in length, respectively, and exerts pleiotropic functions mediated by three G-protein-coupled receptors, which are preferentially associated with activation of adenylate cyclase: VPAC1, VPAC2, and PAC1 [9]. Whereas VPAC1 and VPAC2 receptors show a comparable high affinity for both VIP and PACAP, the PAC1 receptor binds PACAP with high affinity and VIP with much lower affinity [9, 10].

In the clinical context, PACAP has previously attracted attention because of its role as a potent trigger of migraine headaches, which has led to the exploration of strategies to antagonize the PACAP–PAC1 pathway as a potential new therapeutic approach for this significant neurological disorder [8, 11, 12]. However, in support of the pleiotropic nature of PACAP, a broad spectrum of favorable effects on various organs and tissues has also been demonstrated. For example, in the cardiovascular context, PACAP activation of the PAC1 receptor has been shown to inhibit protein synthesis in cardiac fibroblasts and to stimulate the release of atrial natriuretic peptide (ANP) in rat cardiomyocytes in vitro, thus potentially exerting anti-fibrotic effects [13]. In vivo models of cardiotoxicity involving doxorubicin or mitoxantrone administration or irradiation also revealed anti-fibrotic as well as anti-inflammatory and anti-apoptotic effects of PACAP [14–16].

The apolipoprotein E knockout (ApoE−/−) mouse is an established model for studying atherogenesis, and also exhibits a marked systemic inflammatory and pro-fibrotic status in conjunction with a Western-type cholesterol-enriched diet (CED). In addition, we have previously shown that the PAC1 receptor agonist maxadilan attenuates atherosclerosis in ApoE−/− mice fed a high-fat diet [17]. This model has therefore been chosen here to examine the possible involvement of PACAP signaling through PAC1 in the pathogenesis of metabolic stress-induced cardiac fibrosis [18, 19].