# Microbiota alteration is associated with the development of stress-induced despair behavior

Depression is one of the most common types of mental illnesses, affecting up to 7% of the population [1,2]. While improved diagnosis led to appreciation of the frequency of the disorder, better understanding of the mechanisms leading to depression is needed for the development of new therapeutic approaches for this debilitating disease. Based on both human and animal studies, several hypotheses have been proposed to underlie the etiology of depression, including monoamine deficiency, stress response dysregulation, neuronal plasticity deficits, and inflammation [1–3]. Genetic polymorphisms have also been linked to an increased risk for developing depression [2]. `r actionLink(ns("practice_intro1_mystery1"), "However, their prevalence cannot account for the frequency and familial nature of the disorder. Family history can also be viewed as having a “shared environment”, i.e. a shared microbiota composition.", class = "highlight_yellow")`  Therefore, we decided to explore the role of the gut microbiota in the development and maintenance of depressive behavior. The microbiota, the collection of organisms inhabiting various organs, has been increasingly recognized to modulate host physiology4. Changes in gut microbiota composition have been linked to CNS function in animal models and human studies. In most studies, germ free mice show a decreased anxiety phenotype, but an exacerbated response to stress, and have numerous neurochemical disturbances [5–9]. Alteration of gut microbiota composition in despair and anxiety disorders has long been suspected from clinical observations, such as high co-morbidities of colitis and depression [10–12]. In this study, we set out to understand whether and how microbiota alterations contribute to CNS dysfunction and behavioral abnormalities and whether the gut microbiota could be therapeutically targeted to alleviate depression. Here, we show that chronic stress significantly alters intestinal microbiota composition, primarily depleting the Lactobacillus compartment. ROS produced by Lactobacilli can inhibit kynurenine metabolism, a pathway that can negatively impact the brain when dysregulated. Surprisingly, therapeutic administration of L. reuteri to stressed mice improves metabolic homeostasis and corrects stress-induced despair behaviors.