# Changes in gut microbiota composition with age and correlations with gut inflammation in rats

`r actionLink(ns("practice_discussion1_claim1"), "However, their prevalence cannot account for the frequency and familial nature of the disorder. Family history can also be viewed as having a “shared environment”, i.e. a shared microbiota composition.", class = "invisible_yellow")`

Gut bacterial development is a crucial factor affecting host inflammation, immunity and disease [26,27]. However, a study on the functional characterization of gut bacterial strains has not been conducted, and the role of bacteria in different diseases is not completely consistent. We found that the gut bacterial community shifted in a successional manner, and the bacterial community developed with increasing richness and decreasing diversity with age. Lachnospiraceaewas decreased in children with diarrhea, and supplementation with Lachnospiraceaealleviated obesity and inflammation in mice [28,29]. In this study, we found that Lachnospiraceaewas positively associated with the levels of the anti-inflammatory cytokine IL10, suggesting that Lachnospiraceaemay play positive roles in host gut inflammation. Ruminococcus was negatively associated with pro-inflammatory cytokine IFN-γ levels and positively associated with iFABP, suggesting that Ruminococcus may also play positive roles in host gut inflammation. We found that Lactobacilluswas strongly positively associated with LPS levels, an endotoxin that promotes the synthesis and release of various cytokines and inflammatory mediators. Greatly increases in Lactobacillus abundance from the 9th week to 13th week may imply that the body suffers from some abnormal changes and more Lactobacilluswere needed. In addition, Lachnospiraceae, Faecalibacterium, Ruminococcus and Lactobacillus were considered to be related to the expression of short-chain fatty acids (SCFAs) [30–33]. Studies have suggested that SCFAs have an important role in host metabolism, such as improving post-stroke recovery, reducing the development of severe pancreatic insulitis, alleviating psychological problems and influencing the gut-brain axis [34–39]. Bacteroides, Desulfovibrionaceae and Turricibacter were considered to have potential proinflammatory properties in some studies [40–44]. However, we found that Turricibacterwas significantly negatively correlated with the proinflammatory cytokine IL-6, suggesting that Turricibactermay have potential anti-inflammatory properties. There was a decreasing trend of gut inflammation over the sexual maturity stage in this study, which was consistent with the trend of LPS biosynthesis pathway activity in functional prediction.